### ISSUE TITLE
Delay and flicker with eshell-smart

### ISSUE THREAD

**Issue by dieggsy** [cyrus-and/zoom#1]
If you do a `M-x customize-variable eshell-modules-list RET` and check `eshell-smart` and set/save, some weird flickering happens when opening another window from eshell using something like  `find-file-other-window init.el`. Specifically, it seems to kind of oscillate between two sizes, eventually settling on the correct one. This is sort of odd, but is perhaps due to the fact that the functions `eshell-smart-scroll-window` and `eshell-smart-redisplay` deal with window displaying/selection. I haven't yet pinpointed the problem more specifically.

**Comment by cyrus-and** [comment]
I cannot reproduce that, try to describe your current layout (in my case it's just two windows: eshell on the left and the *found* file on the right), frame size (`M-x : (cons (frame-width) (frame-height))`) and `zoom-size` value.

**Comment by cyrus-and** [comment]
OK, I can reproduce it now (`eshell` must be restarted after changing `eshell-modules-list`).

The culprit seems to be:

```el
(defun eshell-refresh-windows (&optional frame)
  "Refresh all visible Eshell buffers."
  (let (affected)
    (walk-windows
     (function
      (lambda (wind)
	(with-current-buffer (window-buffer wind)
	  (if eshell-mode
	      (let (window-scroll-functions) ;;FIXME: Why?
		(eshell-smart-scroll-window wind (window-start))
		(setq affected t))))))
     0 frame)
    (if affected
	(let (window-scroll-functions) ;;FIXME: Why?
	  (eshell-redisplay)))))
```

which calls `walk-windows`, which in turn changes the selected window thus causing the flickering.

It's not a solution but the flickering can be reduced with:

```el
(custom-set-variables
 '(zoom-ignored-major-modes '(eshell-mode)))
```

**Comment by cyrus-and** [comment]
Not entirely true, here's how to reproduce that behavior without `eshell`:

```el
;; `redisplay' is called by `eshell-redisplay'
(add-hook 'window-configuration-change-hook 'redisplay)
```

And I'm not sure if I can do anything about it...

**Comment by cyrus-and** [comment]
a78361f6db1753ad749f5b865f2076579a276971 at least seems to be removing the flickering when windows are selected but not when are created.

**Comment by cyrus-and** [comment]
Using `eshell-currently-handling-window` as an additional guard [here][1] to inhibit the handler further helps but not completely.

[1]: https://github.com/cyrus-and/zoom/blob/a78361f6db1753ad749f5b865f2076579a276971/zoom.el#L141-L146

**Comment by cyrus-and** [comment]
OK I think I got it, here's what happens during an Eshell update triggered by, say, a window split when another buffer is selected:

1. Eshell select its buffer using `(select-window w 'NORECORD)` so Zoom correctly doesn't update the layout;
2. Eshell triggers (for whatever reason) a redisplay (via `sit-for`);
3. the redisplay triggers Zoom which *zooms* the currently selected window (Eshell);
4. Eshell select the original buffer the same as 1, thus leaving the layout in an incoherent state.

This, plus some other weird behaviors which I cannot explain...

I think the best option is to disable `eshell-redisplay` altogether which basically is only used by [`eshell-smart` and `eshell-history`][1]. In the former case [to work around a bug][2] (17 years ago). In both cases I didn't notice any difference after disabling `eshell-redisplay` (but I'm not an avid Eshell user, especially when it comes to its extension modules).

Using the following seems to be a reasonable solution and the best we can have right now.

```el
(advice-add #'eshell-redisplay :override #'ignore)
```

My hunch is that Eshell is doing something fishy with the redraw functions because the incoherent state above also presents some glitches like displaying two filled cursors (instead of the usual outline shown in not focused windows) which should never happen.

[1]: https://github.com/emacs-mirror/emacs/search?utf8=%E2%9C%93&q=eshell-redisplay&type=
[2]: https://github.com/emacs-mirror/emacs/commit/157975e356a04f86bcad1f3503271d10149e7399
