### ISSUE TITLE
not working with EXWM windows

### ISSUE THREAD

**Issue by 11111000000** [cyrus-and/zoom#16]
EXWM windows not resized with that (golden ratio works ok)

**Comment by cyrus-and** [comment]
I'm not an EXVM user myself, but with my setup windows get resized by Zoom, albeit with some flickering (which is even worse with `golden-ratio-mode` and most of the times it doesn't update the sizes).

But sometimes the window is resized but the content is not updated, I noticed that this can be fixed by manually loading Zoom after the login. I suspect that EXWM relies on the order some hooks to manage windows.

What version of Emacs are you using?

**Comment by pmiddend** [comment]
I can confirm this still occurs, and `golden-ratio` does work.

Any way to debug this further? I'm using emacs 29.4

**Comment by cyrus-and** [comment]
@pmiddend you can help by providing a proper issue report with detailed information, how to reproduce, configurations, screenshots, etc. I don't use EXWM.
