### ISSUE TITLE
Odd behavior of zoom

### ISSUE THREAD

**Issue by jsirex** [cyrus-and/zoom#24]
Steps: `C-x 3 C-x 2 C-down (windmove-down) C-x 3`
Last window shrinks way much, but there are lots of space...
Now do C-up (windmove-up) - layout gets fixed.

![zoom](https://user-images.githubusercontent.com/1346569/56471334-d7fc1680-6459-11e9-8e68-d8f4cf4ae74c.png)

Used `(setq zoom-size '(0.618 . 0.618))`

**Comment by cyrus-and** [comment]
This is sadly the expected behavior, what Zoom does:

1. balance windows with `balance-windows`;
2. resize the current window using the computed size (and let Emacs arrange the other windows).

I don't feel like writing the balancing function myself because I'm afraid it will be a nightmare of corner cases (just take a look at the `balance-windows` code) so I opted for the easier, yet approximate, algorithm above.
