### ISSUE TITLE
Zoom font-size together with windows?

### ISSUE THREAD

**Issue by 0o153** [cyrus-and/zoom#26]
Lovely people from internet, thank you for this package ^w^

I wonder about adding font-size increase/decrease - main window with larger font, side windows with smaller ones. Would anyone find something like this useful? Well, and even if not, would you have any hints or thoughts on how it could be implemented?

Cheers!

**Comment by cyrus-and** [comment]
Hey, glad you like it!

This is a too niche (yet possibly quite cool!) feature to incorporate, but it should be fairly easy to implement in your own init file, for example:

```lisp
(advice-add 'zoom--resize :after 'my/zoom-text)
;; (advice-remove 'zoom--resize 'my/zoom-text)

(defun my/zoom-text ()
  ;; zoom out text in other windows
  (mapc (lambda (window)
          (with-selected-window window
            (text-scale-set -1)))
        (window-list))
  ;; zoom in text in current window
  (text-scale-set 1))
```

The problem with this approach is that the text scale is changed buffer-wise and not window-wise and currently I don't really know how to achieve that. There is [this][1] patch that would add support for per-window face support  but I don't know if it made it to Emacs 27 and solutions like the one employed by [hiwin][2] that makes use of overlays, but apparently are (quoting the above patch) not perfect:

> The existing support for per-window overlays isn't sufficient, since 1) overlays affect only buffer text, and so can't affect non-text face-configured regions like the beyond EOB text area.

If we come up with a reasonable solution I could add hooks so that advising is not needed.

[1]: https://lists.gnu.org/archive/html/emacs-devel/2018-06/msg00224.html
[2]: https://github.com/yoshida-mediba/hiwin-mode

**Comment by cyrus-and** [comment]
> but I don't know if it made it to Emacs 27

Yep it did make it, and actually the author wrote a [package][1] that demonstrates that feature, use it like:

```lisp
(custom-set-variables
 '(window-highlight-mode t))

(custom-set-faces
 '(window-highlight-focused-window ((t (:height 1.5)))))
```

> If we come up with a reasonable solution I could add hooks so that advising is not needed.

Well, or we can simply use one of the two mentioned packages that apparently work well with zoom.

For example, with [hiwin][2]:

```lisp
(hiwin-activate)

(custom-set-faces
 '(hiwin-face ((t (:height 0.7)))))
```

[1]: https://github.com/dcolascione/emacs-window-highlight
[2]: https://github.com/yoshida-mediba/hiwin-mode

**Comment by cyrus-and** [comment]
Closing now, I hope the above helps. Feel free to comment if you have any questions.
