### ISSUE TITLE
the top window shrinks too much when a larger minibuffer appears

### ISSUE THREAD

**Issue by blue0513** [cyrus-and/zoom#5]
It's a great emacs package! (I used to use `golden-ratio.el` before, but it is a bit slow unfortunately)

However I face an unexpected behavior, when i have two split windows and open a minibuffer, the top window will shrink too much (even the top window is selected) as bellow.

![untitled3](https://user-images.githubusercontent.com/8979468/31557438-a6a4fb46-b083-11e7-9c09-12c59f2c7c90.gif)

Of course, i know one of the reasons is my higher minibuffer height (I widen the minibuffer height using `(setq ivy-height 30)` for [ivy](https://github.com/abo-abo/swiper) ). 
If the minibuffer height is default (10 lines), the top window will not be shrink too much.

Do you have any solutions to prevent this behavior?

And my `zoom.el` setting is 
```
(custom-set-variables
 '(zoom-mode t))
(custom-set-variables
 '(zoom-size '(0.618 . 0.618)))
```

**Comment by cyrus-and** [comment]
Hey, thanks, so great to hear that! :)

I'm having hard time reproducing this: what happens when I fire up ivy (e.g., `M-x`) is that the minibuffer is enlarged and the remaining windows are naturally resized keeping the *original proportion*, because when the minibuffer is selected Zoom does nothing (in fact you can even resize them manually; I should fix this...).

Looking closely at the screencast, that doesn't seem a 0.618 ratio neither I see the "Z" on the mode line. How is that?

About #6, is a possible step towards the solution but it happens to cause infinite recursion in certain situations (that I still need to properly pinpoint). I'll look into this...

**Comment by cyrus-and** [comment]
OK the problem with #6 is also that it only work when the minibuffer is enlarged, e.g., ivy; it doesn't automatically work with the vanilla `M-x`. d36b9b5892615c3937f4a4d4bd9242f870c4bc50 should do the trick. Let me know if it works.

Anyway, I'm still interested in:

> Looking closely at the screencast, that doesn't seem a 0.618 ratio neither I see the "Z" on the mode line. How is that?

because I'd like to be able to reproduce your issue.

**Comment by blue0513** [comment]
Thank for your polite review!! (In fact it is my first pull request and was nervous a bit)

> it doesn't automatically work with the vanilla M-x. d36b9b5 should do the trick. Let me know if it works.

OK! I'll check it and remake my PR. 

> I'm having hard time reproducing this: what happens when I fire up ivy (e.g., M-x)

Oh, really. hmm...I'll check deeply my `init.el` again after commenting out other packages.

> Looking closely at the screencast, that doesn't seem a 0.618 ratio 

Sorry for the confusion. At the screencast, I set the ratio 0.5 but usually I set 0.618 ratio.

> neither I see the "Z" on the mode line. How is that?

I use [diminish.el](https://github.com/emacsmirror/diminish) to hide most of the modes. And at the screencast, I also *diminish* `zoom-mode` (but it was enabled, of course)

**Comment by cyrus-and** [comment]
> (In fact it is my first pull request and was nervous a bit)

No worries! Thanks for your reply and time. :)

> I'll check it and remake my PR.

It shouldn't be necessary, as d36b9b5892615c3937f4a4d4bd9242f870c4bc50 should fix this issue, or do you still experience it?

**Comment by blue0513** [comment]
[d36b9b5](https://github.com/cyrus-and/zoom/commit/d36b9b5892615c3937f4a4d4bd9242f870c4bc50) 
Excellent!! I installed this version, and it looks perfect! 

Thanks for your quick reply and commit :)

**Comment by cyrus-and** [comment]
FYI 633046edbc42502fd93464f91c43eab75d7d5dd3 just changed the default behavior, you may want to add the following to your init file:

```el
(custom-set-variables
 '(zoom-minibuffer-preserve-layout nil))
```

**Comment by blue0513** [comment]
thanks!!
